# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534653e05ade90680a3afbebf9ca7db6cfa5da256d744ef0f26f4621b1caf6ccfe7754bc6d1c310245f4db519ae151b581bf27fdad269e193baae319d5276e89

test:
  secret_key_base: cc79ec78bfb14362813d5a17de0183e36d178286a4866dabd116939cc3de86ec4db9026fff658eb3bdd02e7c7ee3ede8af522f144496012b1c5c0ac6284e2f73

# Do not keep production secrets in the repository,
# instead read values from the environment.
# dotenv導入する
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
